### ISSUE TITLE
PySide.QtUiTools is missing in Nuke 10.x so the application fails to load.

### ISSUE THREAD

**Issue by extrinsicmedia** [AtomicConductor/conductor_client#82]
Line 4 in the pyside_utils.py causes a failure when loading Nuke 10.x:
```
from PySide import QtGui, QtCore, QtUiTools
```

Error:
```
Traceback (most recent call last):
  File "/Users/vectorthirteen/.nuke/menu.py", line 18, in <module>
    from conductor import submitter
  File "/Users/vectorthirteen/conductor_client/conductor/submitter.py", line 20, in <module>
    from conductor.lib import  conductor_submit, pyside_utils, common, api_client, loggeria, package_utils
  File "/Users/vectorthirteen/conductor_client/conductor/lib/pyside_utils.py", line 4, in <module>
    from PySide import QtGui, QtCore, QtUiTools
ImportError: cannot import name QtUiTools
```

**Comment by sozawa** [comment]
I realize it's been a while since this was logged, but I think this was addressed some time ago.  However, we specifically made updates to PySide and QtUiTools in v2.4.7 to help with support for Maya 2017.  Can you please review and see if that doesn't fix your issue?
https://github.com/AtomicConductor/conductor_client/releases/tag/v2.4.7
